### ISSUE TITLE
SimpleHistory not working

### ISSUE THREAD

**Issue by bachig26** [Eisa01/mpv-scripts#79]
```
mpv https://www.youtube.com/watch?v=DTrZuu8KImg
   cplayer: Resuming playback. This behavior can be disabled with --no-resume-playback.
     demux: Not seekable, but enabling seeking on user request.
   cplayer:  (+) Video --vid=1 (*) (vp9 1920x1080 23.976fps)
   cplayer:  (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
display-tags: File tags:
display-tags:  Uploader: The Voice Reupload
display-tags:  Channel_URL: https://www.youtube.com/channel/UC4_oZRsrJWMkQvubV2bhWpg
quality_menu: fetching available formats...
SimpleHistory:
SimpleHistory: stack traceback:
SimpleHistory:  ...ps/mpv/current/portable_config/scripts/SimpleHistory.lua:442: in function 'read_log_table'
SimpleHistory:  ...ps/mpv/current/portable_config/scripts/SimpleHistory.lua:1253: in function 'delete_log_entry'
SimpleHistory:  ...ps/mpv/current/portable_config/scripts/SimpleHistory.lua:2044: in function 'write_log'
SimpleHistory:  ...ps/mpv/current/portable_config/scripts/SimpleHistory.lua:2158: in function 'history_fileonly_save'
SimpleHistory:  ...ps/mpv/current/portable_config/scripts/SimpleHistory.lua:2219: in function 'handler'
SimpleHistory:  mp.defaults:510: in function 'call_event_handlers'
SimpleHistory:  mp.defaults:552: in function 'dispatch_events'
SimpleHistory:  mp.defaults:503: in function <mp.defaults:502>
SimpleHistory:  [C]: at 0x7ff6427c9d60
SimpleHistory:  [C]: at 0x7ff6427c8440
SimpleHistory: Lua error: ...ps/mpv/current/portable_config/scripts/SimpleHistory.lua:457: attempt to index local 'p' (a nil value)
        vd: Using hardware decoding (d3d11va).
   cplayer: AO: [wasapi] 48000Hz stereo 2ch float
   cplayer: VO: [gpu] 1920x1080 d3d11[nv12]
   cplayer: Saving state.
   cplayer: Sending hook command failed. Removing hook.
    ffmpeg: tls: mbedtls_ssl_read returned -0x0
    ffmpeg: https: Will reconnect at 3506160 in 0 second(s), error=I/O error.
   cplayer:
   cplayer: Exiting... (Quit)

PS D:\cmder
λ mpv https://www.youtube.com/watch?v=DTrZuu8KImg
   cplayer: Resuming playback. This behavior can be disabled with --no-resume-playback.
     demux: Not seekable, but enabling seeking on user request.
   cplayer:  (+) Video --vid=1 (*) (vp9 1920x1080 23.976fps)
   cplayer:  (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
display-tags: File tags:
display-tags:  Uploader: The Voice Reupload
display-tags:  Channel_URL: https://www.youtube.com/channel/UC4_oZRsrJWMkQvubV2bhWpg
quality_menu: fetching available formats...
SimpleHistory:
SimpleHistory: stack traceback:
SimpleHistory:  ...ps/mpv/current/portable_config/scripts/SimpleHistory.lua:442: in function 'read_log_table'
SimpleHistory:  ...ps/mpv/current/portable_config/scripts/SimpleHistory.lua:1253: in function 'delete_log_entry'
SimpleHistory:  ...ps/mpv/current/portable_config/scripts/SimpleHistory.lua:2044: in function 'write_log'
SimpleHistory:  ...ps/mpv/current/portable_config/scripts/SimpleHistory.lua:2158: in function 'history_fileonly_save'
SimpleHistory:  ...ps/mpv/current/portable_config/scripts/SimpleHistory.lua:2219: in function 'handler'
SimpleHistory:  mp.defaults:510: in function 'call_event_handlers'
SimpleHistory:  mp.defaults:552: in function 'dispatch_events'
SimpleHistory:  mp.defaults:503: in function <mp.defaults:502>
SimpleHistory:  [C]: at 0x7ff6427c9d60
SimpleHistory:  [C]: at 0x7ff6427c8440
SimpleHistory: Lua error: ...ps/mpv/current/portable_config/scripts/SimpleHistory.lua:457: attempt to index local 'p' (a nil value)
        vd: Using hardware decoding (d3d11va).
   cplayer: AO: [wasapi] 48000Hz stereo 2ch float
   cplayer: VO: [gpu] 1920x1080 d3d11[nv12]
   cplayer: Saving state.
   cplayer: Sending hook command failed. Removing hook.
   cplayer:
   cplayer: Exiting... (Quit)
```
